services:
  immudb:
    image: codenotary/immudb:latest
    volumes:
      - db-data:/var/lib/immudb
    ports:
      - 8080:8080

  immulogsd:
    build:
      context: .
      dockerfile: Dockerfile
    image: lootek/go-immulogsd:latest
    command:
      - --storage
      - immudb
      - --immudb-host
      - immudb
    ports:
      - 8000:8000
    depends_on:
      - immudb

volumes:
  db-data:
